<div class="alert alert-warning" role="alert">
<center>ESTATÍSTICA APLICADA A COMPUTAÇAO</center>
<center>LISTA 10A</center>
<center>ALUNO: Maria Eduarda Pereira de Souza Melo</center>
</div>

## Questão 1:

(a) Alturas de balões de ar quente: Variável quantitativa, pois a altura é expressa em números.

(b) Capacidades de carga de caminhonetes: Variável quantitativa, pois a capacidade de carga é contável e finita.
    
(c) Cores dos olhos de modelos: Variáveis qualitativas pois as cores dos olhos se distinguem por características não numéricas.
    
(d) Números de identidade de estudantes: Quantitativa, pois descrevem quantidades e podemos, de certa forma, organizar esses números.
    
(e) Respostas em uma pesquisa de opinião: Qualitativa pois se distinguem por características não numéricas.

## Questão 2:

In [1]:
import pandas as pd
dados= {'Sexo':['F','M','F','F','M','M','F','F','F','M','F','M','M','M','M','M','F','F','M','M','F','F','M','M','F','F','M','M','F','F','F','M','M','F','M','M','F','M','F','F','F','M'], 
'Predileta':['H','M','P','H','C','H','M','P','H','C','P','M','G','G','M','M','P','G','G','P','M','G','H','M','P','G','C','H','M','P','M','G','H','M','P','G','M','P','M','M','P','M'],
'Nota':[5,8,8,6,5,6,8,4,2,6,8,2,4,9,7,1,8,5,9,5,8,6,3,5,5,5,7,4,7,7,6,6,9,8,5,6,7,5,5,5,9,8]}
df = pd.DataFrame(dados)
df

   Sexo Predileta  Nota
0     F         H     5
1     M         M     8
2     F         P     8
3     F         H     6
4     M         C     5
5     M         H     6
6     F         M     8
7     F         P     4
8     F         H     2
9     M         C     6
10    F         P     8
11    M         M     2
12    M         G     4
13    M         G     9
14    M         M     7
15    M         M     1
16    F         P     8
17    F         G     5
18    M         G     9
19    M         P     5
20    F         M     8
21    F         G     6
22    M         H     3
23    M         M     5
24    F         P     5
25    F         G     5
26    M         C     7
27    M         H     4
28    F         M     7
29    F         P     7
30    F         M     6
31    M         G     6
32    M         H     9
33    F         M     8
34    M         P     5
35    M         G     6
36    F         M     7
37    M         P     5
38    F         M     5
39    F         M     5
40    F         P     9
41    M         M     8

A variável quantitativa é: Nota

As variáveis qualitativas são: Sexo e Predileta

A tabela da frequência da variável Sexo é dada por:

In [2]:
freq_sexo = pd.DataFrame(df['Sexo'].value_counts())
freq_sexo

   Sexo
F    21
M    21

A tabela da frequência da variável Predileta é dada por:

In [3]:
freq_pred= pd.DataFrame(df['Predileta'].value_counts())
freq_pred

   Predileta
M         14
P         10
G          8
H          7
C          3

## Questão3:

As variáveis quantitativas são: RES,RENDA,ident.

As variáveis qualitativas são: PAP, GI

A tabela de frequência da variável qualitativa PAP é dada por:

In [4]:
d = {'ident.':[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40], 'PAP':[0,0,1,0,1,1,0,1,1,1,0,1,0,0,0,0,1,0,0,1,1,1,0,0,0,1,1,0,1,0,1,1,1,1,1,1,1,1,1,1],
         'GI':[3,3,2,2,3,1,3,3,3,2,2,1,2,2,3,2,3,3,3,3,3,3,3,2,2,3,1,3,2,3,3,2,3,1,1,1,3,3,3,3],
         'RES':[4,4,4,5,4,1,2,3,6,4,6,4,4,6,3,5,3,4,4,4,5,5,5,4,8,4,5,3,4,5,5,2,5,2,6,8,3,5,5,3],
         'RENDA':[10.3,15.4,9.6,5.5,9.0,2.4,4.1,8.4,10.3,4.6,18.6,7.1,12.9,8.4,19.3,10.4,8.9,12.9,5.1,12.2,5.8,12.9,7.7,1.1,7.5,5.8,7.2,8.6,5.1,2.6,7.7,2.4,4.8,2.1,4.0,12.5,6.8,3.9,9.0,10.9]}
novodf = pd.DataFrame(d)
freq_PAP= pd.DataFrame(novodf['PAP'].value_counts())
freq_PAP

   PAP
1   24
0   16

A tabela de frequência da variável qualitativa GI é dada por:

In [5]:
freq_GI = pd.DataFrame(novodf['GI'].value_counts())
freq_GI

   GI
3  23
2  11
1   6